ansible/galaxy-api

openapi/openapi.yaml

Revert "Rm /pulp/tasks from OAS, add generic /tasks API"

---

openapi/openapi.yaml

Create initial OpenAPI spec that describes set of API endspoints
provided by Galaxy API v3.
Closes ansible/galaxy-dev#30

Add initial OpenAPI spec

---

openapi/openapi.yaml

Add back pagination schema and params
Fixes https://github.com/ansible/galaxy-dev/issues/31

Add pagination schema

---

openapi/openapi.yaml

Namespace, Tenant, bits of User models
Related https://github.com/ansible/galaxy-dev/issues/33

Namespace, Tenant, bits of User models  (33)

---

galaxy_api/api/migrations/0001_initial.py
galaxy_api/api/models.py

Add Namespace and NamespaceLink database models.
Fixes: ansible/galaxy-dev#47

Add namespace models

---

openapi/openapi.yaml

Add /collections endpoints, and some of the models
Don't know what CollectionVersion will look like or
if it will be different than v2.
Related https://github.com/ansible/galaxy-dev/issues/34

Add params/responses/schema for /collections and /download endpoints (34)

---

openapi/openapi.yaml

Add NamespaceLink, flesh out Namespace fields

---

openapi/openapi.yaml

Related https://github.com/ansible/galaxy-dev/issues/36

[WIP] Add params/responses for /users/* and /profile endpoints

---

openapi/openapi.yaml

Move namespaces endpoints to _UI

---

galaxy_api/auth/admin.py
galaxy_api/settings.py
galaxy_api/urls.py

Setup django admin, and add admin setup for galaxy_api.auth

Add Django admin

---

openapi/openapi.yaml

Update Tag model to reflect the response
from the v1 API /tags
Issue: ansible/galaxy-dev#58
TODO: search params  (later pr?)

Rm /search/tags, add /_ui/tags #58

---

openapi/openapi.yaml

https://github.com/ansible/galaxy-dev/issues/35
Add /imports/collections and /_ui/imports/* endpoints
/imports/collections/
/imports/collections/{import_id}
/ui/imports/collections/
/ui/imports/collections/{import_id}
Rough out a UiCollectionImport schema
CollectionImport schema based on /v2/collection-imports

Flesh out collection imports related api for issue #35

---

openapi/openapi.yaml

* Move UI endpoints to `UI:` prefixed tags.
* Fix operation ids and titles.
* Add `_ui/` prefix to profile and users endpoints.

OpenAPI: Group UI endpoints

---

Pipfile
Pipfile.lock
galaxy_api/api/models.py
galaxy_api/api/pagination.py
galaxy_api/api/ui/serializers/__init__.py
galaxy_api/api/ui/serializers/collection.py
galaxy_api/api/ui/serializers/namespace.py
galaxy_api/api/ui/urls.py
galaxy_api/api/ui/viewsets/__init__.py
galaxy_api/api/ui/viewsets/collection.py
galaxy_api/api/v3/viewsets.py
galaxy_api/pulp/client.py
galaxy_api/pulp/galaxy.py
galaxy_api/settings.py

API: Collection API endpoints for UI

---

openapi/openapi.yaml

* Remove collection modify requests
* Add schemas for collection endpoints for UI.

OpenAPI: Update spec for collection endpoints

---

galaxy_api/api/urls.py
galaxy_api/api/views.py
tests/api/base.py
tests/api/test_api_views.py
tests/api/test_v3_collections.py

API root endpoint returns list of available API versions and
current version.
Closes: ansible/galaxy-dev#80

Implement API root endpoint

---

bindings/openapi.yaml
galaxy_api/api/ui/urls.py
galaxy_api/api/ui/viewsets/__init__.py
galaxy_api/api/ui/viewsets/tags.py
tests/api/test_api_ui_tags.py

API(UI): Add tags list endpoint

---

openapi/openapi.yaml

Update OAS for ui collection details
Fixes: ansible/galaxy-dev#85

Update openapi schema for ui collection detail views (fixes #85)

---

galaxy_api/api/v3/viewsets.py
galaxy_api/settings.py

Implement artifact download endpoint

---

galaxy_api/api/ui/serializers/__init__.py
galaxy_api/api/ui/urls.py
galaxy_api/api/ui/viewsets/__init__.py
galaxy_api/api/ui/viewsets/namespace.py

- Adds a `my-namespaces` api endpoint that returns a list of namespaces that the current user owns
- Remove links and resources from the `my-namespaces` and `namespaces` list views.

Add my namespaces view set.

---

bindings/openapi.yaml
galaxy_api/api/ui/viewsets/collection.py

- Exclude docs blob from collection list calls
- include only `version`, `id`, `_created`, `artifact` in all versions list on collection detail.

Filter out extra data on collection requests.

---

bindings/openapi.yaml
galaxy_api/api/ui/viewsets/collection.py

- Add tags param to bindings
- Correctly handle list params

Enable tags on the API

---

galaxy_api/api/v3/viewsets.py

Since why or if a publish works will likely be common troubleshooting issue.

Log a little info about publish errors and success

---

galaxy_api/api/ui/viewsets/namespace.py
tests/api/test_api_ui_namespace_viewsets.py
tests/api/test_api_v3_viewsets.py
tests/api/x_rh_identity.py

Enforces ns or syseng perms on write

---

galaxy_api/api/ui/viewsets/namespace.py
tests/api/test_api_ui_namespace_viewsets.py

On my-namespace list, return all if user is in partner-engineers

---

galaxy_api/api/v3/viewsets.py

Fix publish error (no 'prefix' in str format)

---

galaxy_api/api/admin.py
galaxy_api/auth/admin.py

Make groups searchable on namespace form:
Show group members on group form:

Show users in group admin form, make groups searchable on namespace form

---

galaxy_api/api/ui/viewsets/namespace.py

modifying changes done in https://github.com/ansible/galaxy-api/pull/136
while creating a namespace, an identification might not be registered in the database yet, the namespace should still be created with provided identificators

 Accept not yet registered ids while creating namespace

---

galaxy_api/api/v3/viewsets.py
galaxy_api/common/metrics.py

Some custom metrics for:
- collection_import_attempts
- collection_import_failures
- collection_import_successes
- collection_artifact_download_attempts
- collection_artifact_download_successes
- collection_artifact_download_failures

Add metrics for col import and downloads
