ansible/galaxy-api

galaxy_api/fields.py
openapi/openapi.yaml

Start of an openapi.yaml to describe the 'v3' API.
Mostly still based on https://github.com/alikins/galaxy-api-swaggerhub
Some changes:
- /api/v* is now part of the server url, so the paths look like '/namespaces/' or 'collections/'
- rough out the current security/authz though that will change
- added /namespaces/  CRUD stuff
Not included yet:
- any pagination or error formatting changes
- model changes related to the looser coupling between:
- Collection, CollectionVersion and CollectionVersionArtifacts
- Namespaces and Collection*
- User model changes
- api endpoints that are analogs to pulp apis

[WIP] Openapi spec

---

openapi/openapi.yaml

The response from a /tasks/{task_id} can
include task type specific details in 'detail'
field, but it may make sense to have a url
resource for each task type (ie, '/collection-imports/{task_id}'
or possible '/tasks/collection-imports/{task_id}')
swagger view: https://petstore.swagger.io/?url=https://raw.githubusercontent.com/alikins/galaxy-api/openapispec_tasks/openapi/openapi.yaml

Rm /pulp/tasks from OAS, add generic /tasks API

---

openapi/openapi.yaml

Add generic Error and ErrorItem schemas
Add NotFound/Unauthorized responses that use the
Error schema and add as examples to GET / for now.
Fixes https://github.com/ansible/galaxy-dev/issues/32
(at least as far as possible without actually defining
the real endpoints yet)

Add generic Error and ErrorItem schemas  (galaxy-dev#32)

---

galaxy_api/api/pagination.py
galaxy_api/settings.py

Add custom LimitOffsetPagination class, that returns data
in a format defined in API spec and uses path only links.
Fixes: ansible/galaxy-dev#50

Implement limit offset pagination

---

openapi/openapi.yaml

As per https://github.com/ansible/galaxy-dev/issues/55 and parts of https://github.com/ansible/galaxy-dev/issues/56 since they start colliding.
This is the "public" part of the API changes for /collections and collection versions

Use v2 style response for /collections, rm /search/collections, etc #55

---

openapi/openapi.yaml

Namespace creation and deletion is not currently allowed
via API.
DependsOn: #45

OpenAPI: Remove namespace create and delete endpoints

---

openapi/openapi.yaml

Add the following fields to `Namespace` schema:
- `resource_page`
DependsOn: #47

 OpenAPI: Add namespace resource fields

---

openapi/openapi.yaml

Rationale:
Collection upload API v2 is designed against REST API best practices.
Artifact upload operation does not create a new collection resource.
It rather creates a new collection version, though it's implicit side
effect of uploading artifact and import process.
Renaming downloads API to artifacts and moving upload endpoint there
seems most logical, because artifact upload \ download operations
are complimentary and uploading an artifact creates an artifact
resource that can be downloaded then by detail URL.
DependsOn: #46

OpenAPI: Move collections upload to artifacts API

---

openapi/openapi.yaml

`/imports/collection/{id}` has all the information we need for the UI, so I'm getting rid of `_ui/imports/collection{id}` because it's redundant and missing critical information.

Remove ui import detail endpoint

---

openapi/openapi.yaml

Use the default Djanfo Rest Framework style
pagination instead of the JSONAPI style.
The default django rest framework pagination
style is described at
https://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination
``` json
{
"count": 5
"next": "/namespaces/?page=5&page_size=1",
"previous": "/namespaces/?page=3&page_size=1"
"results": [
{
"name": "my_namespace"
}
]
}
```
Use drf pagination style 'page' and 'page_size' query
paramaters.
Update PageInfo.
Issue: ansible/galaxy-dev#76

Use drf style pagination

---

openapi/openapi.yaml

This reverts commit ba40b00a76839572ce88954e0c3628f34c75bf09, reversing
changes made to 06262666586243ba2cf87bb4ce04dee1b9206667.
This returns the pagination style to limit/offset instead
of the drf default page/page_size style.

Revert "Merge pull request #58 from alikins/oas_use_drf_pagination_76"

---

galaxy_api/api/ui/serializers/collection.py

Passthrough CollectionVersion id field returned by pulp API.
depends on: pulp/pulp_ansible#191

Return raw id field for collections and versions

---

bindings/openapi.yaml
galaxy_api/api/pagination.py
galaxy_api/api/ui/serializers/__init__.py
galaxy_api/api/ui/serializers/collection.py
galaxy_api/api/ui/viewsets/collection.py
galaxy_api/api/v3/viewsets.py
tests/api/test_v3_collections.py

This patch fixes limit offset pagination in proxy API
endpoints related to latest changes in pulp pagination.
Fixes: ansible/galaxy-api#90

Fix pagination in ui API

---

bindings/openapi.yaml
galaxy_api/api/ui/viewsets/collection.py
galaxy_api/api/v3/viewsets.py
tests/api/test_api_ui_collection_viewsets.py
tests/api/test_api_v3_viewsets.py

* Add new UI endpoint to set \ unset certified attribute at the
collection version.
* Split GalaxyCollectionsApi pulp client into two classes:
- GalaxyCollectionsApi
- GalaxyCollectionVersionsApi
* Fixed pulp client mocks not checking presense of mocked method
by building spec for mocks (`spec=True`).
Fixes: ansible/galaxy-dev#73

Implement certified set \ unset endpoint

---

galaxy_api/api/urls.py
galaxy_api/api/views.py

Since ansible-galaxy appends a '/api' to the end of
any configured galaxy url, if 'cloud.redhat.com/api/automation-hub/'
is the configured url, ansible-galaxy tries
'cloud.redhat.com/api/automation-hub/api/'.
So add a redirect from /api/automation-hub/api/ to
/api/automation-hub/

Handle ansible-galaxy always appending '/api' to urls

---

galaxy_api/api/views.py
tests/api/test_api_views.py

ie, available_versions on GET /api/automation-hub/
is {'v3': 'v3/'} instead of {'v3': '/api/automation-hub/v3'}
so ansible-galaxy can use it as a relative path to it's
configured server url.
For ex ansible.cfg:
[galaxy_server.local_hub]
url=http://localhost:5001/api/automation-hub/
ansible-galaxy will have to check '/' for api root
now, and use the value of available_versions to
find the right api path.

Make the 'v3' api path relative to root prefix

---

galaxy_api/api/v3/viewsets.py

The StreamingHttpResponse() needs an iterable, so
use Requests response.iter_content(). Using
response.content directly doesn't work.
Fixes: ansible/galaxy-dev#117
After the change, `ansible-galaxy collection install` to a local galaxy/ah will work.
Direct http examples after change:
```
(ansible-py3) [newswoop:F29:ansible (devel % u=)]$ http --verbose --download http://localhost:5001/api/automation-hub/v3/artifacts/collections/alikins.collection_ntp.0.1.182
GET /api/automation-hub/v3/artifacts/collections/alikins.collection_ntp.0.1.182 HTTP/1.1
Accept: */*
Accept-Encoding: identity
Connection: keep-alive
Host: localhost:5001
User-Agent: HTTPie/0.9.9
HTTP/1.1 200 OK
Allow: GET, HEAD, OPTIONS
Connection: close
Content-Type: application/octet-stream
Date: Thu, 19 Sep 2019 18:48:59 GMT …
```

Fix malformed download responses for dev installs

---

galaxy_api/api/ui/viewsets/namespace.py

…es/86
Implement
- 'name=namespace_name' that filters against namespace name
- 'company=company_name' that filters against namespace company
- 'keywords=foo' that filters against namespace name
- 'sort=name' / 'sort=-name' to order results.
Other sort fields are 'company' and 'id'
Fixes: ansible/galaxy-dev#86

Add namespace query params (keywords,name, company) and 'sort' param

---

galaxy_api/api/urls.py
galaxy_api/api/views.py

If ansible-galaxy gets a 301 or 302 redirect from
a server, when it follows the new Location, it does
not include any authentication info.
Since ansible-galaxy also always appends '/api'
which lacks a trailing '/', there is always at
least one redirect plus the redirect from
$real_url/api -> $real_url.
Which means requests to / to get the ApiRootView
with the available versions and auth url info,
ansible-galaxy doesn't send auth.
But if the redirect is a 307 or 308, it will follow.
So make the $real_url/api -> $real_url redirect a
307. Otherwise ansible-galaxy doesn't work against
Automation Hub.

Return 307 for ApiRootView for ansible-galaxy

---

galaxy_api/api/v3/viewsets.py
tests/api/test_api_v3_viewsets.py

This is related to https://github.com/ansible/ansible/issues/63210
If pulp returned an empty list for a collection version, galaxy-api
CollectionVersionViewset() would return a 200 and an empty list.
Pulp may return an empty list if the collection doesn't exist.
ansible-galaxy expects a 404 to be returned if the collection
doesn't exist.

Make an empty /collections/{ns}/{n} a 404

---

galaxy_api/api/v3/viewsets.py

galaxy_pup.api_client.APIClient.request()
doesn't set auth headers the same way
other higher level calls do. So make sure
it sets the auth headers.
Otherwise the basic auth connection to pulp_ansible fails on publish

Fix auth connecting to pulp api.

---

bindings/openapi.yaml
galaxy_api/api/ui/urls.py
galaxy_api/api/ui/viewsets/collection.py
galaxy_api/api/v3/serializers.py
galaxy_api/api/v3/urls.py
galaxy_api/api/v3/viewsets.py
tests/api/test_api_v3_viewsets.py

Add `PUT /api/automation-hub/v3/collections/{ns}/{name}/` for updating a Collection (so that 'deprecated' can be updated).
WIP since it needs tests and other cleanup.

Make collection deprecated update-able #129

---

galaxy_api/api/ui/urls.py

Both NamespaceViewSet and MyNamespaceViewSet were registered to
the url reverse of 'api:ui:namespaces-list' since they both
registered to the router with basename='namespaces'.

Fix the reverse() of MyNamespaceViewSet to 'api:my-namespaces'

---

openapi/ui_openapi.yaml

For now, move the existing defs/schemas to
ui_openapi.yaml and add some warnings about it
being an unstable API.
Fixes: ansible/galaxy-dev#159

Remove /_ui/ API endpoints from openapi.yaml

---

galaxy_api/api/utils.py
galaxy_api/api/v3/serializers.py

Fix 500's on imports with invalid filenames
Make CollectionUploadSerializer raise a drf
ValidationError if the filename isn't the right
format instead of a ValueError.
Raising a ValidationError causes django/drf to return
a 400 status code instead of the 500 returned for the
unhandled ValueError.
Also log the error message at error level, and add
specific info like the filename and version string to
the error message to make it easier to troubleshoot.

Fix 500 on filename value error

---

galaxy_api/api/exceptions.py

For some endpoints, the query params received by galaxy-api
are passed to the pulp endpoints. But for some cases the
galaxy_pulp openapi generated bindings will raise a
galaxy_pulp.ApiTypeError (subclass of galaxy_pulp.OpenApiException).
This is raises before the request is made.
Previously, OpenApiException would result in exception_handler
returning None which causes DRF to return a 500 status code.
Fix by handling OpenApiException errors in the
drf exception_handle and returning a 400 status code instead.

Return 400 instead of 500 for galaxy_pulp client ValueErrors

---

.travis.yml
.yamllint
bindings/openapi.yaml
openapi/openapi.yaml
openapi/ui_openapi.yaml
tox.ini

Make this repo passing the yamllint test and add/update the tox target
to harmonize with what other components within `ansible` namespace are
doing.
Namely:
* `ansible/ansible-runner`
* `ansible/awx`
* `ansible-network/ansible_collections.vyos.vyos`
* `ansible/workshops`
Signed-off-by: Yanis Guenane <yguenane@redhat.com>

Enable yamllint and make the repo yamllintable

---

galaxy_api/settings.py

Generate a request_id for requests in local
dev config by setting REQUEST_ID_HEADER=None.
This generates a request_id for each request.
Prod/CI/QA env will need to set this back to:
REQUEST_ID_HEADER = 'HTTP_X_REQUEST_ID'
Attach a request_id filter to the 'console'
handler so console request include the request_id
log record field.
Add a root logger at ERROR level that logs to console.
Add a 'galaxy_api' logger at INFO level to catch app
logging.
**NOTE:** Since this turns on auto generation of request_id by default, the config settings.py used for CI/PROD will need to set it back. See https://github.com/RedHatInsights/e2e-deploy/pull/1022 for a pr to do that.

log: Include request_id, add root logger

---

galaxy_api/api/v3/viewsets.py
galaxy_api/common/parsers.py

In ansible-galaxy versions 2.9, the body of the multipart/form
POST'ed as part of the 'publish' command causes the default
django/drf multipart/form parsers to ignore the 'sha256' content.
When the parser ignores it, the sha256 value is None, which
the galaxy-api publish code considers an optional value.
So when the publish / import is passed to pulp api via
galaxy_pulp, the pulp side doesn't check that the artifacts
sha256sum matches the 'sha256' value (since it is None).
This adds a custom parser that subclasses the drf 'MultiPartParser'
but does some pre-processing on the request body stream to
correct it before it is sent to the base MultiPartParser.
Add test case simulating ansible-galaxy 2.9
Fixes ansible/galaxy-dev#246

server side fix for multipart/form 'sha256' problems #246
